
# Auto-generated by generate_models.py
from sqlalchemy import (
    Table, Column, Integer, String, Text, ForeignKey, MetaData, func, DDL
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata

# ----------------------------------------
# Tablo: table_3
table_3 = Table(
    "table_3",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_3_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_4
table_4 = Table(
    "table_4",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_4_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_5
table_5 = Table(
    "table_5",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_5_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_6
table_6 = Table(
    "table_6",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_6_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_7
table_7 = Table(
    "table_7",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_7_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_1
table_1 = Table(
    "table_1",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_1_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_2
table_2 = Table(
    "table_2",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_2_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_8
table_8 = Table(
    "table_8",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_8_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_9
table_9 = Table(
    "table_9",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_9_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_10
table_10 = Table(
    "table_10",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_10_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_11
table_11 = Table(
    "table_11",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_11_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_12
table_12 = Table(
    "table_12",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_12_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_13
table_13 = Table(
    "table_13",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_13_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_14
table_14 = Table(
    "table_14",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_14_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_15
table_15 = Table(
    "table_15",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_15_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_16
table_16 = Table(
    "table_16",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_16_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_17
table_17 = Table(
    "table_17",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_17_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_18
table_18 = Table(
    "table_18",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_18_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_19
table_19 = Table(
    "table_19",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_19_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_21
table_21 = Table(
    "table_21",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_21_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_20
table_20 = Table(
    "table_20",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_20_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_22
table_22 = Table(
    "table_22",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_22_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_23
table_23 = Table(
    "table_23",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_23_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_24
table_24 = Table(
    "table_24",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_24_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_25
table_25 = Table(
    "table_25",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_25_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_26
table_26 = Table(
    "table_26",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_26_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_27
table_27 = Table(
    "table_27",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_27_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_28
table_28 = Table(
    "table_28",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_28_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_29
table_29 = Table(
    "table_29",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_29_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_30
table_30 = Table(
    "table_30",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_30_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_31
table_31 = Table(
    "table_31",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_31_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_32
table_32 = Table(
    "table_32",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_32_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_33
table_33 = Table(
    "table_33",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_33_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: table_34
table_34 = Table(
    "table_34",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_34_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)
# ----------------------------------------
# Tablo: related_table_39
related_table_39 = Table(
    "related_table_39",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".related_table_39_id_seq\'::regclass)'),
    Column("table_20_id", INTEGER),
    Column("extra", TEXT),
    # ForeignKey: table_20_id → table_20(id)
    Column("table_20_id", Integer, ForeignKey("table_20.id")),
)
# ----------------------------------------
# Tablo: related_table_36
related_table_36 = Table(
    "related_table_36",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".related_table_36_id_seq\'::regclass)'),
    Column("table_1_id", INTEGER),
    Column("info", TEXT),
    # ForeignKey: table_1_id → table_1(id)
    Column("table_1_id", Integer, ForeignKey("table_1.id")),
)
# ----------------------------------------
# Tablo: related_table_37
related_table_37 = Table(
    "related_table_37",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".related_table_37_id_seq\'::regclass)'),
    Column("table_2_id", INTEGER),
    Column("notes", TEXT),
    # ForeignKey: table_2_id → table_2(id)
    Column("table_2_id", Integer, ForeignKey("table_2.id")),
)
# ----------------------------------------
# Tablo: related_table_38
related_table_38 = Table(
    "related_table_38",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".related_table_38_id_seq\'::regclass)'),
    Column("table_10_id", INTEGER),
    Column("description", TEXT),
    # ForeignKey: table_10_id → table_10(id)
    Column("table_10_id", Integer, ForeignKey("table_10.id")),
)
# ----------------------------------------
# Tablo: related_table_40
related_table_40 = Table(
    "related_table_40",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".related_table_40_id_seq\'::regclass)'),
    Column("table_35_id", INTEGER),
    Column("comment", TEXT),
    # ForeignKey: table_35_id → table_35(id)
    Column("table_35_id", Integer, ForeignKey("table_35.id")),
)
# ----------------------------------------
# Tablo: table_35
table_35 = Table(
    "table_35",
    metadata,
    Column("id", INTEGER, primary_key=True, nullable=False, default='nextval(\'"public".table_35_id_seq\'::regclass)'),
    Column("col1", TEXT),
    Column("col2", TEXT),
    Column("col3", TEXT),
    Column("col4", TEXT),
    Column("col5", TEXT),
    Column("col6", TEXT),
    Column("col7", TEXT),
    Column("col8", TEXT),
    Column("col9", TEXT),
    Column("col10", TEXT),
)


# ========================================
# View’lar
# View: vw_table_2_simple
vw_table_2_simple = Table(
    "vw_table_2_simple",
    metadata,
    Column("id", INTEGER),
    Column("col1", TEXT),
    Column("col2", TEXT),
    info={"is_view": True}
)
# View: vw_table_1_join_36
vw_table_1_join_36 = Table(
    "vw_table_1_join_36",
    metadata,
    Column("table1_id", INTEGER),
    Column("table1_col1", TEXT),
    Column("related36_id", INTEGER),
    Column("related36_info", TEXT),
    info={"is_view": True}
)


# ========================================
# Fonksiyon Tanımları (DDL)
# Aşağıdaki fonksiyonlar doğrudan veritabanında CREATE OR REPLACE ... şeklinde çalıştırılmalıdır
# Function: make_uppercase
# === DDL Start ===
"""
CREATE OR REPLACE FUNCTION public.make_uppercase(input_text text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN upper(input_text);
END;
$function$
"""
# === DDL End ===

# Function: trg_table_1_to_upper
# === DDL Start ===
"""
CREATE OR REPLACE FUNCTION public.trg_table_1_to_upper()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.col1 := upper(NEW.col1);
    RETURN NEW;
END;
$function$
"""
# === DDL End ===



# ========================================
# Trigger Tanımları (DDL)
# Aşağıdaki trigger’lar veritabanında CREATE TRIGGER ... şeklinde çalıştırılmalıdır
# Trigger: table_1_insert_to_upper (Table: table_1)
# === DDL Start ===
"""
CREATE TRIGGER table_1_insert_to_upper BEFORE INSERT ON table_1 FOR EACH ROW EXECUTE FUNCTION trg_table_1_to_upper()
"""
# === DDL End ===

