"""add col2 to vw_table_1_join_36

Revision ID: 1740dcf2e288
Revises: b3ff111228e3
Create Date: 2025-06-13 10:42:59.067789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1740dcf2e288'
down_revision: Union[str, None] = 'b3ff111228e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1,
        col2
       FROM table_2
      WHERE (NOT (col1 IS NULL));""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1 AS col_one,
        col2
       FROM table_2
      WHERE (NOT (col1 IS NULL));""")
    # ### end Alembic commands ###
