"""yeni degisiklik

Revision ID: 69f1618ebdf8
Revises: 11543a4f9e6b
Create Date: 2025-06-13 11:10:07.568178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f1618ebdf8'
down_revision: Union[str, None] = '11543a4f9e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1,
        col2
       FROM table_2
      WHERE ((NOT (col1 IS NULL)) AND (NOT (col2 IS NULL)));""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1,
        col2
       FROM table_2
      WHERE ((col1 IS NOT NULL) AND (col2 IS NOT NULL));""")
    # ### end Alembic commands ###
