"""add views

Revision ID: 82e57e751be8
Revises: 9e5dab05b9d6
Create Date: 2025-06-11 10:11:35.293311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e57e751be8'
down_revision: Union[str, None] = '9e5dab05b9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1,
        col2
       FROM table_2
      WHERE (NOT (col1 IS NULL));""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1,
        col2
       FROM table_2
      WHERE (col1 IS NOT NULL);""")
    # ### end Alembic commands ###
