"""add views

Revision ID: a0d5c3a9ac8e
Revises: 
Create Date: 2025-06-10 10:52:33.273090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d5c3a9ac8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_table_40',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_35_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_35_id'], ['table_35.id'], name='related_table_40_table_35_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='related_table_40_pkey')
    )
    op.create_table('table_30',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_30_pkey')
    )
    op.create_table('table_17',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_17_pkey')
    )
    op.create_table('table_21',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_21_pkey')
    )
    op.create_table('table_28',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_28_pkey')
    )
    op.create_table('table_34',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_34_pkey')
    )
    op.create_table('table_1',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('table_1_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_1_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('table_6',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_6_pkey')
    )
    op.create_table('related_table_37',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_2_id'], ['table_2.id'], name='related_table_37_table_2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='related_table_37_pkey')
    )
    op.create_table('table_32',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_32_pkey')
    )
    op.create_table('table_9',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_9_pkey')
    )
    op.create_table('table_5',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_5_pkey')
    )
    op.create_table('table_2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_2_pkey')
    )
    op.create_table('table_27',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_27_pkey')
    )
    op.create_table('related_table_39',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_20_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_20_id'], ['table_20.id'], name='related_table_39_table_20_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='related_table_39_pkey')
    )
    op.create_table('table_11',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_11_pkey')
    )
    op.create_table('related_table_36',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_1_id'], ['table_1.id'], name='related_table_36_table_1_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='related_table_36_pkey')
    )
    op.create_table('table_26',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_26_pkey')
    )
    op.create_table('table_31',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_31_pkey')
    )
    op.create_table('table_23',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_23_pkey')
    )
    op.create_table('table_7',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_7_pkey')
    )
    op.create_table('table_25',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_25_pkey')
    )
    op.create_table('table_24',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_24_pkey')
    )
    op.create_table('table_20',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_20_pkey')
    )
    op.create_table('table_15',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_15_pkey')
    )
    op.create_table('table_12',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_12_pkey')
    )
    op.create_table('table_8',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_8_pkey')
    )
    op.create_table('table_33',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_33_pkey')
    )
    op.create_table('table_10',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('table_10_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_10_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('table_22',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_22_pkey')
    )
    op.create_table('table_4',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_4_pkey')
    )
    op.create_table('table_18',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_18_pkey')
    )
    op.create_table('related_table_38',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_10_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_10_id'], ['table_10.id'], name='related_table_38_table_10_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='related_table_38_pkey')
    )
    op.create_table('table_35',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_35_pkey')
    )
    op.create_table('table_13',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_13_pkey')
    )
    op.create_table('table_19',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_19_pkey')
    )
    op.create_table('table_14',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_14_pkey')
    )
    op.create_table('table_3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_3_pkey')
    )
    op.create_table('table_29',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_29_pkey')
    )
    op.create_table('table_16',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('col10', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='table_16_pkey')
    )
    # ### end Alembic commands ###
