"""alter vw_table_2_simple col1→col_one

Revision ID: fd465a5b4ba2
Revises: 82e57e751be8
Create Date: 2025-06-11 10:28:46.253956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd465a5b4ba2'
down_revision: Union[str, None] = '82e57e751be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1 AS col_one,
        col2
       FROM table_2
      WHERE (NOT (col1 IS NULL));""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP VIEW vw_table_2_simple""")
    op.execute("""CREATE VIEW vw_table_2_simple AS  SELECT id,
        col1,
        col2
       FROM table_2
      WHERE (NOT (col1 IS NULL));""")
    # ### end Alembic commands ###
